### ISSUE TITLE
Have more specific close statuses

### ISSUE THREAD

**Issue by DariusParvin** [boltlabs-inc/tezos-contract#43]
@marsella pointed out that right now if you look at a contract with status CLOSED, you cannot tell which close flow it took without referencing anything else.

It seems like it would be useful to have more specific close statuses to differentiate the different close flows. Note that it wouldn't affect the gas or storage costs.

**Comment by DariusParvin** [comment]
thoughts @indomitableSwan  @jakinyele?

**Comment by indomitableSwan** [comment]
I believe we already settled this on slack in the affirmative.

**Comment by DariusParvin** [comment]
After talking just now, I'll wait until @marsella or @indomitableSwan  confirm we want this.

**Comment by indomitableSwan** [comment]
@marsella Thoughts?

**Comment by marsella** [comment]
These should no longer be _necessary_. I believe the polling service and general zeekoe architecture work without these statuses; we extra zeekoe statuses to indicate which close flow we're in, instead of using `PendingClose` for everything.

We can still add them if we want to be able to examine a contract and determine what happened after the fact. For example, a party looking through their closed channels cannot determine how they were closed right now. We could solve that by adding more close statuses on either the zeekoe or the contract end. But it is not necessary for a functional protocol.

**Comment by indomitableSwan** [comment]
@jakinyele Given the above, are we safe to close this issue?

**Comment by jakinyele** [comment]
@indomitableSwan I think so
